apiVersion : apps/v1
kind: Deployment
metadata:
  name: bkubenerntesdeployimage1 
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bkubenerntesdeployimage1
  template:
    metadata:
      labels:
        app: bkubenerntesdeployimage1 
    spec:
      containers:
        - name: bkubenerntesdeployimage1 
          image: march30acr.azurecr.io/bkubenerntesdeployimage1
          ports:
          - containerPort: 80